name: flutter_login
# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  dio: ^5.1.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.3.2
  shared_preferences: ^2.1.0
  connectivity_plus: ^6.0.3

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.10+1

  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
